envVarGroups:
  - name: lendledger-config
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
      - key: JAVA_OPTS
        value: -Xmx384m -XX:+UseContainerSupport
      - key: DB_PORT
        value: "5432"
      - key: DB_HOST
        value: REPLACE_ME
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: REPLACE_ME
      - key: REDIS_URL
        value: REPLACE_ME
      - key: JWT_SECRET
        value: REPLACE_ME
      - key: INTERNAL_API_KEY
        value: REPLACE_ME

services:
  - type: web
    name: lendledger-auth
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    dockerfilePath: ./deploy/docker/auth.Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: lendledger-config

  - type: web
    name: lendledger-loan
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    dockerfilePath: ./deploy/docker/loan.Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: lendledger-config
      - key: AUTH_SERVICE_URL
        value: REPLACE_ME
      - key: PAYMENT_SERVICE_URL
        value: REPLACE_ME

  - type: web
    name: lendledger-payment
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    dockerfilePath: ./deploy/docker/payment.Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: lendledger-config
      - key: LOAN_SERVICE_URL
        value: REPLACE_ME

  - type: web
    name: lendledger-notification
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    dockerfilePath: ./deploy/docker/notification.Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: lendledger-config

  - type: web
    name: lendledger-gateway
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    dockerfilePath: ./deploy/docker/gateway.Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: lendledger-config
      - key: AUTH_SERVICE_URL
        value: REPLACE_ME
      - key: LOAN_SERVICE_URL
        value: REPLACE_ME
      - key: PAYMENT_SERVICE_URL
        value: REPLACE_ME
      - key: NOTIFICATION_SERVICE_URL
        value: REPLACE_ME
      - key: CORS_ORIGIN
        value: REPLACE_ME
